DROP TABLE IF EXISTS PRODUCTS;  
CREATE TABLE PRODUCTS (  
ID INT PRIMARY KEY,  
NAME VARCHAR(50),
DESCRIPTION VARCHAR(250),
PRICE FLOAT
);

DROP TABLE IF EXISTS SALES;
CREATE TABLE SALES (
ID INT PRIMARY KEY,
PRODUCT_ID INT NOT NULL,
QUANTITY INT NOT NULL
)